import { BookPage } from '../types';

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  isStreaming?: boolean;
  suggestions?: AiSuggestion[];
  toolCalls?: AiToolCall[];
}

export interface AiSuggestion {
  id: string;
  target: 'selection' | 'chapter' | 'title';
  originalText?: string;
  suggestedText: string;
  rationale?: string;
  status: 'pending' | 'applying' | 'applied' | 'rejected' | 'failed';
  errorMessage?: string;
}

export interface AiToolCall {
  name: string;
  args: any;
  status: 'pending' | 'executed' | 'cancelled';
  result?: any;
}

export interface BookContextPayload {
  bookTitle?: string;
  bookAuthor?: string;
  genre?: string;
  currentChapterTitle?: string;
  currentChapterNumber?: number;
  totalChapters?: number;
  selectedText?: string;
  currentChapterContent?: string;
  chapterList?: { pageNumber: number; title: string }[];
  requestedChapterContent?: string;
  requestedChapterNumber?: number;
}

export interface StreamChatOptions {
  messages: { role: string; content: string }[];
  bookContext: BookContextPayload;
  action?: string;
  chapterLookup?: Record<number, string>;
  onChunk: (chunkText: string) => void;
  onToolCall?: (call: { name: string; args: any }) => void;
  onDone: (fullText: string) => void;
  onError: (errorMsg: string) => void;
}

/**
 * Generates a stable deterministic ID for a suggestion
 */
export function generateStableSuggestionId(
  suggestedText: string,
  originalText?: string,
  index: number = 0
): string {
  let hash = 0;
  const str = `${index}_${(originalText || '').trim()}_${suggestedText.trim()}`;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return `sugg_${Math.abs(hash).toString(36)}`;
}

/**
 * Parses <<<SUGGESTION>>> blocks generated by Gemini
 */
export function extractSuggestionsFromText(text: string): AiSuggestion[] {
  const suggestions: AiSuggestion[] = [];
  const regex = /<<<SUGGESTION>>>([\s\S]*?)<<<END_SUGGESTION>>>/gi;
  let match;
  let index = 0;

  while ((match = regex.exec(text)) !== null) {
    const block = match[1];
    const origMatch = /(?:ORIGINAL|ORIGINAL_TEXT|ORIG):\s*([\s\S]*?)(?=(?:SUGGESTED|SUGGESTION|REPLACEMENT|REWRITE):|$)/i.exec(block);
    const suggMatch = /(?:SUGGESTED|SUGGESTION|REPLACEMENT|REWRITE):\s*([\s\S]*?)(?=(?:RATIONALE|REASON|WHY):|$)/i.exec(block);
    const ratMatch = /(?:RATIONALE|REASON|WHY):\s*([\s\S]*?)$/i.exec(block);

    const suggestedText = suggMatch ? suggMatch[1].trim() : '';
    const originalText = origMatch ? origMatch[1].trim() : undefined;
    if (suggestedText) {
      suggestions.push({
        id: generateStableSuggestionId(suggestedText, originalText, index++),
        target: 'selection',
        originalText,
        suggestedText,
        rationale: ratMatch ? ratMatch[1].trim() : undefined,
        status: 'pending',
      });
    }
  }

  return suggestions;
}

/**
 * Streams chat responses from the server-side Gemini endpoint
 */
export function streamAiChat(options: StreamChatOptions): () => void {
  const controller = new AbortController();
  let isExplicitlyAborted = false;
  let hasDoneOrErrorCalled = false;

  (async () => {
    let accumulatedText = '';
    try {
      const response = await fetch('/api/ai/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: options.messages,
          bookContext: options.bookContext,
          action: options.action,
          chapterLookup: options.chapterLookup,
          stream: true,
        }),
        signal: controller.signal,
      });

      if (!response.ok) {
        let errMessage = 'Gemini API request failed. Check the server configuration.';
        try {
          const errData = await response.json();
          if (errData.details) {
            errMessage = `${errData.error || 'Gemini request failed'}: ${errData.details}`;
          } else if (errData.error) {
            errMessage = errData.error;
          }
        } catch {
          // ignore
        }
        hasDoneOrErrorCalled = true;
        options.onError(errMessage);
        return;
      }

      if (!response.body) {
        hasDoneOrErrorCalled = true;
        options.onError('Readable stream not supported by browser.');
        return;
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder('utf-8');
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith('data:')) continue;

          const jsonStr = trimmed.replace(/^data:\s*/, '').trim();
          if (!jsonStr) continue;

          try {
            const data = JSON.parse(jsonStr);

            if (data.type === 'chunk' && data.text) {
              accumulatedText += data.text;
              options.onChunk(data.text);
            } else if (data.type === 'tool_call') {
              if (options.onToolCall) {
                options.onToolCall({ name: data.name, args: data.args });
              }
            } else if (data.type === 'done') {
              hasDoneOrErrorCalled = true;
              options.onDone(data.fullText || accumulatedText);
            } else if (data.type === 'error') {
              hasDoneOrErrorCalled = true;
              const errMsg = data.details ? `${data.error || 'Gemini request failed'}: ${data.details}` : (data.error || 'Gemini API request failed. Check the server configuration.');
              options.onError(errMsg);
            }
          } catch (parseErr) {
            console.warn('SSE JSON parse error:', parseErr);
          }
        }
      }

      // If finished cleanly without explicit 'done' event
      if (!hasDoneOrErrorCalled) {
        hasDoneOrErrorCalled = true;
        options.onDone(accumulatedText);
      }
    } catch (err: any) {
      if (err.name === 'AbortError') {
        // Generation cancelled explicitly by author
        if (isExplicitlyAborted) {
          options.onDone(accumulatedText ? `${accumulatedText}\n\n*(Generation stopped)*` : '*(Generation stopped)*');
        } else {
          options.onError('Gemini API request was interrupted.');
        }
        return;
      }
      console.error('Fetch stream error:', err);
      if (!hasDoneOrErrorCalled) {
        options.onError('Gemini API request failed. Check the server configuration.');
      }
    }
  })();

  // Return cancel function
  return () => {
    isExplicitlyAborted = true;
    controller.abort();
  };
}

/**
 * Translates manuscript or arbitrary text via server-side Gemini
 */
export async function translateText(
  text: string,
  sourceLang: string = 'Auto',
  targetLang: string = 'English'
): Promise<string> {
  const response = await fetch('/api/ai/translate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      text,
      sourceLang,
      targetLang,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error || 'Translation request failed.');
  }

  const data = await response.json();
  return data.translation || '';
}
